# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
org.gradle.parallel=true
android.uniquePackageNames=false
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.dependency.excludeLibraryComponentsFromConstraints=true
org.gradle.configuration-cache=false

android.onlyEnableUnitTestForTheTestedBuildType=false
android.dependency.useConstraints=true
android.r8.optimizedResourceShrinking=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
